apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: http-nginx
spec:
  ports:
  - name: 3000-http
    port: 3002
    protocol: TCP
    targetPort: http
  selector:
    app: nginx
  type: ClusterIP
